# Generated by Django 3.1.4 on 2020-12-09 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Planning'), (1, 'Active'), (2, 'Control'), (3, 'Completed')], default=0)),
                ('start_time', models.DateTimeField(blank=True)),
                ('completion_time', models.DateTimeField(blank=True)),
                ('expected_completion_time', models.DateTimeField(blank=True)),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(related_name='watched_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.IntegerField(choices=[(0, 'Planning'), (1, 'Active'), (2, 'Control'), (3, 'Completed')])),
                ('new', models.IntegerField(choices=[(0, 'Planning'), (1, 'Active'), (2, 'Control'), (3, 'Completed')])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='tasks.task')),
            ],
        ),
    ]
